import {useEffect,useRef,useState} from 'react';
import {GuidedApi} from './guided-api';
import {isGuidedEnded,type GuidedAction,type GuidedSession,type GuidedSetup,type GuidedFeedback} from './guided-types';
import {VoiceSession,type GuidedViewState,type VoiceDependencies} from './voice-session';
const blank:GuidedViewState={session:null,visible:true,busy:false,error:'',audioBlocked:false,transport:'idle',remaining:0};
const labels={created:'Ready to connect',connecting:'Connecting',coach_speaking:'Coach speaking — microphone off',listening:'Your turn — microphone enabled after playback settles',reviewing:'Reviewing your attempt — microphone off',paused:'Paused — microphone released',reconnecting:'Reconnecting',finished:'Session finished',failed:'Session ended with an error'};
const decisions={retry:'Try this exercise again',next:'Next exercise',simplify:'A simpler exercise',finish:'Practice complete',clarify:'Please clarify your response'};
function Feedback({feedback,visible}:{feedback:GuidedFeedback;visible:boolean}){return <section className="guided-feedback" aria-label="Latest feedback"><h3>Latest feedback</h3>{visible?<><dl>{feedback.strength&&<><dt>Strength</dt><dd>{feedback.strength}</dd></>}{feedback.priority_correction&&<><dt>Priority correction</dt><dd>{feedback.priority_correction}</dd></>}{feedback.corrected_example&&<><dt>Corrected example</dt><dd>{feedback.corrected_example}</dd></>}{feedback.evidence_basis==='transcript'&&feedback.evidence_quote&&<><dt>Transcript evidence</dt><dd>{feedback.evidence_quote}</dd></>}</dl></>:<><p>Feedback ready. Reveal the prompt to read the details.</p><p>{feedback.priority_correction?'Correction available':'No correction recorded'}</p></>}{feedback.evidence_basis==='uncertain'&&<p>Transcript evidence is uncertain. No confident assessment is available.</p>}<p>{decisions[feedback.decision]}</p></section>;}
export function GuidedSnapshot({view,onAction,onVisibility,onRecover}:{view:GuidedViewState;onAction:(a:GuidedAction)=>void;onVisibility:(v:boolean)=>void;onRecover:()=>void}){
 const s=view.session;if(!s)return null;const ended=isGuidedEnded(s);const prompt=s.prompts[s.prompt_index];const latest=s.turns.at(-1);const disconnected=view.transport==='disconnected';const disabled=view.busy||ended;
 return <section className="panel guided-session" aria-label="Guided Voice session"><div className="guided-heading"><h2>Guided Voice</h2><button className="small-button" aria-pressed={view.visible} onClick={()=>onVisibility(!view.visible)}>{view.visible?'Hide Prompt':'Show Prompt'}</button></div><p role="status">{labels[s.state]}</p><p className="fine">{view.remaining} seconds until the server session limit · Exercise {Math.min(s.prompt_index+1,s.prompts.length)} of {s.prompts.length} · {s.attempts_on_prompt} attempts on this exercise</p>{view.visible?prompt&&<blockquote className="guided-prompt">{prompt.text}</blockquote>:<p className="guided-prompt">Prompt hidden. Listen to the coach.</p>}{latest&&<>{view.visible&&<section aria-label="Latest saved transcript"><h3>Your latest response</h3><p>{latest.transcript}</p></section>}<Feedback feedback={latest.feedback} visible={view.visible}/></>}{view.audioBlocked&&<div className="system-banner"><p>Coach audio is blocked by your browser. Your microphone stays off.</p><button className="primary" onClick={onRecover}>Enable coach audio</button></div>}{view.error&&<p role="alert" className="error">{view.error}</p>}{!ended&&<div className="guided-controls"><button className="small-button" disabled={disabled||disconnected||s.state==='paused'} onClick={()=>onAction('replay')}>Replay</button><button className="small-button" disabled={disabled||disconnected||s.state==='paused'||s.attempts_on_prompt>=s.max_retries+1} onClick={()=>onAction('retry')}>Try again</button><button className="primary" disabled={disabled||disconnected||s.muted||s.state!=='listening'} onClick={()=>onAction('done')}>I’m done</button>{s.state==='paused'?<button className="small-button" disabled={disabled} onClick={()=>onAction('resume')}>Resume</button>:<button className="small-button" disabled={ended} onClick={()=>onAction('pause')}>Pause</button>}<button className="small-button" aria-pressed={s.muted} disabled={disabled||disconnected||s.state==='paused'} onClick={()=>onAction(s.muted?'unmute':'mute')}>{s.muted?'Unmute microphone':'Mute microphone'}</button>{disconnected&&<button className="primary" disabled={disabled||view.remaining<=0} onClick={()=>onAction('reconnect')}>Reconnect</button>}<button className="danger-button" onClick={()=>onAction('finish')}>End session</button></div>}{ended&&s.recap&&<section aria-label="Guided recap"><h3>Practice recap</h3><p>{s.recap.practiced_exercises} exercises practiced · {s.recap.completed_attempts} completed attempts</p>{view.visible?<><p>{s.recap.focus}</p><p>Next practice: {s.recap.next_practice}</p></>:<p>Reveal the prompt to read your saved recap details.</p>}</section>}{ended&&!s.recap&&<p>No recap is available. You can check saved guided history.</p>}</section>;
}
export function GuidedSessionView({api,setup,available,verified,unavailableReason,dependencies,ownerKey=null,ownerScope,onController,onActive}:{api:GuidedApi;setup:GuidedSetup|null;available:boolean;verified:boolean;unavailableReason?:string;dependencies?:VoiceDependencies;ownerKey?:unknown;ownerScope?:()=>unknown;onController?:(c:VoiceSession|null)=>void;onActive?:(active:boolean)=>void}){
 const [view,setView]=useState<GuidedViewState>(blank),[reset,setReset]=useState(0);const controller=useRef<VoiceSession|null>(null);const scope=useRef(ownerScope);scope.current=ownerScope;const callback=useRef(onController);callback.current=onController;const active=useRef(onActive);active.current=onActive;const renderedOwner=useRef(ownerKey);
 useEffect(()=>{renderedOwner.current=ownerKey;const c=new VoiceSession(api,v=>{setView(v);active.current?.(!!v.session);},dependencies,()=>scope.current?scope.current():ownerKey);controller.current=c;setView({...blank,visible:setup?.prompt_visible??true});active.current?.(false);callback.current?.(c);const hide=()=>c.dispose();window.addEventListener('pagehide',hide);return()=>{window.removeEventListener('pagehide',hide);c.dispose();if(controller.current===c)controller.current=null;callback.current?.(null);};},[api,ownerKey,dependencies,reset,verified,available]);
 const safe=renderedOwner.current===ownerKey?(verified&&available?view:{...blank,visible:view.visible}):blank;
 if(safe.session)return <><GuidedSnapshot view={safe} onAction={a=>{void controller.current?.action(a);}} onVisibility={v=>{void controller.current?.toggle(v);}} onRecover={()=>{void controller.current?.recoverAudio();}}/>{isGuidedEnded(safe.session)&&<button className="primary" onClick={()=>setReset(n=>n+1)}>Set up another guided session</button>}</>;
 return <section className="guided-setup" aria-label="Guided Voice setup"><h2>Guided Voice</h2><p>The AI coach speaks one short exercise at a time. Listen, then respond when it is your turn. Your saved professional profile, scenario, goal, and context guide practice.</p><p className="fine">Your microphone audio is sent to the voice provider while listening. Prompts, transcripts, feedback, and a recap are saved in your private workspace. The app does not retain raw guided audio; provider retention policies still apply.</p><button className="small-button" aria-pressed={safe.visible} onClick={()=>{void controller.current?.toggle(!safe.visible);}}>{safe.visible?'Hide Prompt':'Show Prompt'}</button><p className="fine">{safe.visible?'Prompt text will be shown.':'Prompt text and reconstructive feedback will be hidden.'}</p>{!available&&<p role="status">Guided Voice is unavailable. {unavailableReason??'The server has not enabled guided voice.'}</p>}{!verified&&<p className="fine">Sign in with a verified account to start Guided Voice.</p>}{!setup&&<p>Choose a scenario above to continue.</p>}<button className="primary" disabled={!available||!verified||!setup||safe.busy} onClick={()=>{if(setup&&available&&verified)void controller.current?.start({...setup,prompt_visible:safe.visible});}}>{safe.busy?'Connecting guided session…':'Start guided session'}</button>{safe.busy&&<button className="text-button" onClick={()=>{controller.current?.dispose();setReset(n=>n+1);}}>Cancel guided connection</button>}{safe.error&&<p className="error" role="alert">{safe.error}</p>}</section>;
}

export function GuidedHistory({api,verified,ownerKey}:{api:GuidedApi;verified:boolean;ownerKey:unknown}){
 const [rows,setRows]=useState<GuidedSession[]>([]),[opened,setOpened]=useState<GuidedSession|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const lifetime=useRef<{abort:AbortController;owner:unknown}|null>(null);
 useEffect(()=>{const scope={abort:new AbortController(),owner:ownerKey};lifetime.current=scope;setRows([]);setOpened(null);setError('');setBusy(false);if(verified){setBusy(true);api.list(scope.abort.signal).then(s=>{if(lifetime.current===scope&&!scope.abort.signal.aborted)setRows(s);}).catch(()=>{if(lifetime.current===scope&&!scope.abort.signal.aborted)setError('Could not load guided history. Please return to this page to retry.');}).finally(()=>{if(lifetime.current===scope&&!scope.abort.signal.aborted)setBusy(false);});}return()=>{scope.abort.abort();if(lifetime.current===scope)lifetime.current=null;};},[api,verified,ownerKey]);
 const safe=lifetime.current?.owner===ownerKey&&verified;const items=safe?rows:[];const detail=safe&&opened&&isGuidedEnded(opened)?opened:null;
 async function run(work:(signal:AbortSignal)=>Promise<void>){const scope=lifetime.current;if(!scope||!verified||busy)return;setBusy(true);setError('');try{await work(scope.abort.signal);}catch{if(lifetime.current===scope&&!scope.abort.signal.aborted)setError('Guided history action was not confirmed. Reload history before trying again.');}finally{if(lifetime.current===scope&&!scope.abort.signal.aborted)setBusy(false);}}
 return <section className="panel guided-history" aria-label="Guided Voice history"><h2>Guided Voice history</h2><p className="fine">Saved guided exercises are separate from Recorded Practice scores. Active prompt text is never shown here.</p>{!verified?<p>Sign in with a verified account to view guided history.</p>:!items.length&&!busy?<p>No saved guided sessions yet.</p>:null}{busy&&<p role="status">Loading guided history…</p>}{error&&<p role="alert" className="error">{error}</p>}{items.map(s=><div className="history-row" key={s.id}><div><h3>Guided session</h3><p>{new Date(s.created_at).toLocaleDateString()} · {labels[s.state]} · {s.turns.length} saved attempts</p></div>{isGuidedEnded(s)&&<button className="small-button" disabled={busy} onClick={()=>{void run(async signal=>{const scope=lifetime.current;const result=await api.get(s.id,signal);if(scope===lifetime.current&&!signal.aborted&&isGuidedEnded(result))setOpened(result);});}}>Review guided session</button>}<button className="text-button danger-text" aria-label={'Delete guided session '+s.id} disabled={busy} onClick={()=>{if(window.confirm('Delete this guided session, its prompts, transcripts, feedback, and recap? This cannot be undone.'))void run(async signal=>{const scope=lifetime.current;await api.delete(s.id,signal);const next=await api.list(signal);if(next.some(r=>r.id===s.id))throw new Error('Deletion was not confirmed.');if(scope===lifetime.current&&!signal.aborted){setRows(next);if(opened?.id===s.id)setOpened(null);}});}}>Delete</button></div>)}{detail&&<section className="guided-readback" aria-label="Saved guided session"><h3>Saved exercises</h3><button className="text-button" onClick={()=>setOpened(null)}>Close guided review</button>{detail.prompts.map(p=><article key={p.id}><h4>Exercise {p.position+1}</h4><blockquote>{p.text}</blockquote>{detail.turns.filter(t=>t.prompt_id===p.id).map(t=><div key={t.id}><p>Attempt {t.attempt}: {t.transcript}</p><Feedback feedback={t.feedback} visible/></div>)}</article>)}{detail.recap&&<section><h3>Practice recap</h3><p>{detail.recap.practiced_exercises} exercises practiced · {detail.recap.completed_attempts} completed attempts</p><p>{detail.recap.focus}</p><p>Next practice: {detail.recap.next_practice}</p></section>}</section>}</section>;
}
