import {fireEvent,render,screen} from '@testing-library/react';
import {it,expect,vi} from 'vitest';import App from './App';
import {act,waitFor} from '@testing-library/react';import {GuidedApi} from './guided-api';import {VoiceTransport} from './voice-session';import {dto,audioSdp,deferred} from './guided-test-doubles';import {emptyProfile,offlineScenarios} from './types';
const sdk=vi.hoisted(()=>({client:null as any}));vi.mock('@supabase/supabase-js',()=>({createClient:()=>sdk.client}));
it('keeps Recorded Practice as default and offers an honest separate unavailable Guided Voice setup/history',async()=>{
 vi.stubGlobal('fetch',vi.fn(async(path:string)=>{if(path.endsWith('/config'))return new Response(JSON.stringify({auth_configured:false,ai_enabled:true,guided_voice_available:false,guided_unavailable_reason:'Voice provider is not configured.'}));throw new Error('offline');}));render(<App/>);await screen.findByText(/Account setup pending/);fireEvent.click(screen.getByRole('button',{name:'Practice studio'}));expect(screen.getByRole('button',{name:'Recorded Practice'})).toHaveAttribute('aria-pressed','true');fireEvent.click(screen.getByRole('button',{name:/Choose scenario: Tell/}));expect(screen.getByRole('button',{name:'Generate my scenario'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Guided Voice'}));expect(screen.queryByRole('button',{name:'Generate my scenario'})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Start guided session'})).toBeDisabled();expect(screen.getByText(/Voice provider is not configured/)).toBeInTheDocument();expect(screen.getByLabelText('Communication goal')).toBeInTheDocument();expect(screen.queryByText('How would you introduce yourself to a prospective employer?')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Practice history'}));expect(screen.getByRole('heading',{name:'Guided Voice history'})).toBeInTheDocument();expect(screen.getByText('Your first conversation belongs here.')).toBeInTheDocument();
});
it('tears down guided audio on owner replacement and opens recorded history in Recorded Practice',async()=>{
 let event:(event:string,s:any)=>void=()=>{};let session:any={user:{id:'owner-a',email_confirmed_at:'2026-01-01'},access_token:'test-only'};sdk.client={auth:{getSession:vi.fn(async()=>({data:{session}})),getUser:vi.fn(async()=>({data:{user:session.user}})),onAuthStateChange:vi.fn(cb=>{event=cb;return {data:{subscription:{unsubscribe:vi.fn()}}};})}};const saved={id:'recorded',scenario_id:'help-desk',goal:'Clarity',question:'Recorded question',example_response:'',context:'',created_at:'2026-01-01',attempts:[]};vi.stubGlobal('fetch',vi.fn(async(path:string)=>new Response(JSON.stringify(path.endsWith('/config')?{auth_configured:true,supabase_url:'https://example.supabase.co',supabase_publishable_key:'public-test',ai_enabled:true,guided_voice_available:true}:path.endsWith('/scenarios')?{scenarios:[]}:path.endsWith('/sessions')?{sessions:[saved]}:path.endsWith('/profile')?emptyProfile:path.endsWith('/sessions/recorded')?saved:{}))));const release=vi.spyOn(VoiceTransport.prototype,'close');vi.spyOn(GuidedApi.prototype,'list').mockResolvedValue([]);
 render(<App/>);await waitFor(()=>expect(fetch).toHaveBeenCalledWith('/api/v1/sessions',expect.anything()));fireEvent.click(screen.getByRole('button',{name:'Practice studio'}));fireEvent.click(screen.getByRole('button',{name:'Guided Voice'}));const before=release.mock.calls.length;act(()=>{session={user:{id:'owner-b',email_confirmed_at:'2026-01-01'},access_token:'test-only-b'};event('SIGNED_IN',session);});expect(release.mock.calls.length).toBeGreaterThan(before);fireEvent.click(screen.getByRole('button',{name:'Practice history'}));await screen.findByRole('button',{name:'Open'});fireEvent.click(screen.getByRole('button',{name:'Open'}));expect(await screen.findByText('Recorded question')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Recorded Practice'})).toHaveAttribute('aria-pressed','true');release.mockRestore();
});
it('clears active guided content while sign-out is pending, even when the auth service later reports a failure',async()=>{
 // Test-only auth/API/media doubles; no live user or provider calls.
 const session={user:{id:'owner-a',email_confirmed_at:'2026-01-01'},access_token:'test-only'};const logout=deferred<any>();sdk.client={auth:{getSession:vi.fn(async()=>({data:{session}})),getUser:vi.fn(async()=>({data:{user:session.user}})),signOut:vi.fn(()=>logout.promise),onAuthStateChange:vi.fn(()=>({data:{subscription:{unsubscribe:vi.fn()}}}))}};vi.stubGlobal('fetch',vi.fn(async(path:string)=>new Response(JSON.stringify(path.endsWith('/config')?{auth_configured:true,supabase_url:'https://example.supabase.co',supabase_publishable_key:'public-test',ai_enabled:true,guided_voice_available:true}:path.endsWith('/scenarios')?{scenarios:offlineScenarios}:path.endsWith('/sessions')?{sessions:[]}:path.endsWith('/profile')?emptyProfile:{}))));vi.spyOn(VoiceTransport.prototype,'acquire').mockResolvedValue();vi.spyOn(VoiceTransport.prototype,'connect').mockImplementation(async exchange=>{await exchange(audioSdp);});vi.spyOn(GuidedApi.prototype,'create').mockResolvedValue(dto());vi.spyOn(GuidedApi.prototype,'connect').mockResolvedValue({sdp:audioSdp,session:{...dto(),state:'coach_speaking',revision:1}});vi.spyOn(GuidedApi.prototype,'command').mockResolvedValue({...dto(),state:'finished',revision:2});
 render(<App/>);await waitFor(()=>expect(fetch).toHaveBeenCalledWith('/api/v1/sessions',expect.anything()));fireEvent.click(screen.getByRole('button',{name:'Practice studio'}));fireEvent.click(screen.getByRole('button',{name:'Guided Voice'}));fireEvent.click(screen.getByRole('button',{name:/Choose scenario: Tell/}));fireEvent.click(screen.getByRole('button',{name:'Start guided session'}));await screen.findByText('PRIVATE TARGET');fireEvent.click(screen.getByRole('button',{name:'Sign out'}));expect(screen.queryByText('PRIVATE TARGET')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Start guided session'})).toBeDisabled();await act(async()=>{logout.resolve({error:new Error('Sign-out could not complete')});await logout.promise;});expect(screen.getByRole('button',{name:'Start guided session'})).toBeEnabled();vi.restoreAllMocks();
});
