import {afterEach,expect,it,vi} from 'vitest';
import {VoiceSession,VoiceTransport,assertAudioOnlySdp} from './voice-session';import {Api} from './api';import {GuidedApi} from './guided-api';
import {audioSdp,deferred,dto,mediaDoubles} from './guided-test-doubles';import type {GuidedSession} from './guided-types';
afterEach(()=>{vi.useRealTimers();vi.restoreAllMocks();});
// TEST-ONLY media, auth, and API responses. No live accounts/providers.
function apiDouble(){const api=new GuidedApi(new Api(async()=>'test',vi.fn()));vi.spyOn(api,'create').mockResolvedValue(dto());vi.spyOn(api,'connect').mockResolvedValue({sdp:audioSdp,session:{...dto(),state:'listening',revision:1}});return api;}
it.each(['created','connecting','coach_speaking','reviewing','paused','reconnecting','finished','failed'] as const)('keeps microphone disabled in authoritative %s',async state=>{
 vi.useFakeTimers();const d=mediaDoubles(),t=new VoiceTransport({},d.deps);await t.acquire();await t.connect(async()=>audioSdp);t.apply({...dto(),state});await vi.advanceTimersByTimeAsync(1000);expect(d.track.enabled).toBe(false);t.close();expect(vi.getTimerCount()).toBe(0);
});
it('handles blocked autoplay with an explicit recovery gesture and a fresh conservative media-tail grace',async()=>{
 vi.useFakeTimers();const d=mediaDoubles(),blocked=vi.fn();vi.mocked(d.audio.play).mockRejectedValueOnce(new Error('autoplay blocked'));const t=new VoiceTransport({onAudioBlocked:blocked},d.deps);await t.acquire();await t.connect(async()=>audioSdp);t.apply({...dto(),state:'listening',revision:1});await vi.advanceTimersByTimeAsync(1000);expect(d.track.enabled).toBe(false);expect(blocked).toHaveBeenCalledWith(true);await t.recoverAudio();await vi.advanceTimersByTimeAsync(499);expect(d.track.enabled).toBe(false);await vi.advanceTimersByTimeAsync(1);expect(d.track.enabled).toBe(true);t.close();
});
it.each([audioSdp+'m=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\n',audioSdp+'m=video 9 UDP/TLS/RTP/SAVPF 96\r\n',audioSdp.replace('audio 9','audio 0'),'v=0\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\n'])('rejects non audio-only or inactive SDP %#',sdp=>expect(()=>assertAudioOnlySdp(sdp)).toThrow('Audio-only'));
it('bounds ICE gathering and releases all local resources before any SDP request',async()=>{
 vi.useFakeTimers();const d=mediaDoubles();d.peer.iceGatheringState='gathering';const exchange=vi.fn();const t=new VoiceTransport({},d.deps);await t.acquire();const pending=t.connect(exchange);const result=expect(pending).rejects.toThrow('timed out');await vi.advanceTimersByTimeAsync(1000);await result;expect(exchange).not.toHaveBeenCalled();expect(d.track.stop).toHaveBeenCalled();expect(d.peer.ontrack).toBeNull();expect(vi.getTimerCount()).toBe(0);
});
it('bounds a peer that never becomes connected after the answer',async()=>{
 vi.useFakeTimers();const d=mediaDoubles();d.peer.setRemoteDescription.mockResolvedValue(undefined);const t=new VoiceTransport({},d.deps);await t.acquire();const pending=t.connect(async()=>audioSdp);const result=expect(pending).rejects.toThrow('timed out');await vi.advanceTimersByTimeAsync(1000);await result;expect(d.track.stop).toHaveBeenCalled();expect(d.audio.srcObject).toBeNull();expect(vi.getTimerCount()).toBe(0);
});
it('closes disconnected peers rather than inventing successful recovery',async()=>{
 const d=mediaDoubles(),issue=vi.fn(),t=new VoiceTransport({onIssue:issue},d.deps);await t.acquire();await t.connect(async()=>audioSdp);d.peer.connectionState='disconnected';d.peer.onconnectionstatechange?.();expect(issue).toHaveBeenCalledWith(expect.stringContaining('Reconnect'));expect(d.track.stop).toHaveBeenCalled();expect(d.peer.ontrack).toBeNull();expect(d.peer.onconnectionstatechange).toBeNull();expect(d.audio.srcObject).toBeNull();
});
it('ignores late old-owner creation and never starts SDP exchange or finishes under the replacement owner',async()=>{
 const d=mediaDoubles(),api=apiDouble(),created=deferred<GuidedSession>(),updates=vi.fn();vi.spyOn(api,'create').mockReturnValue(created.promise);const command=vi.spyOn(api,'command');let owner='a';const c=new VoiceSession(api,updates,d.deps,()=>owner);const pending=c.start({scenario_id:'help-desk',goal:'Clarity',context:'',prompt_visible:true});await vi.waitFor(()=>expect(api.create).toHaveBeenCalled());owner='b';c.dispose();updates.mockClear();created.resolve(dto());await pending;expect(api.connect).not.toHaveBeenCalled();expect(command).not.toHaveBeenCalled();expect(updates).not.toHaveBeenCalled();expect(d.track.stop).toHaveBeenCalled();
});
it('reloads authority after a revision conflict without automatically replaying an evaluated turn or revealing a locally hidden prompt',async()=>{
 const d=mediaDoubles(),api=apiDouble(),current={...dto(),revision:5,state:'reviewing' as const};const command=vi.spyOn(api,'command').mockRejectedValue(new Error('Conflict 409 provider PRIVATE TARGET'));vi.spyOn(api,'get').mockResolvedValue(current);const c=new VoiceSession(api,()=>{},d.deps);await c.start({scenario_id:'help-desk',goal:'Clarity',context:'',prompt_visible:false});await c.action('done');expect(command).toHaveBeenCalledTimes(1);expect(api.get).toHaveBeenCalledTimes(1);expect(c.view.session).toEqual(current);expect(c.view.visible).toBe(false);expect(c.view.error).toContain('No turn was automatically replayed');expect(c.view.error).not.toContain('PRIVATE TARGET');c.dispose(false);
});
it('serializes poll/heartbeat/commands and ignores older revisions while polling',async()=>{
 vi.useFakeTimers();const d=mediaDoubles(),api=apiDouble(),pending=deferred<GuidedSession>();vi.spyOn(api,'heartbeat').mockReturnValue(pending.promise);const command=vi.spyOn(api,'command').mockResolvedValue({...dto(),state:'listening',muted:true,revision:2});const c=new VoiceSession(api,()=>{},d.deps);await c.start({scenario_id:'help-desk',goal:'Clarity',context:'',prompt_visible:true});await vi.advanceTimersByTimeAsync(2000);const muted=c.action('mute');await vi.advanceTimersByTimeAsync(4000);expect(api.heartbeat).toHaveBeenCalledTimes(1);expect(command).not.toHaveBeenCalled();pending.resolve({...dto(),revision:0});await vi.advanceTimersByTimeAsync(1);await muted;expect(api.heartbeat).toHaveBeenCalledTimes(1);expect(command.mock.calls[0][0].revision).toBe(1);expect(c.view.session?.revision).toBe(2);c.dispose(false);expect(vi.getTimerCount()).toBe(0);
});
it('reads finite last-turn completion from the server and stops microphone, playback, polling, and heartbeat',async()=>{
 vi.useFakeTimers();const d=mediaDoubles(),api=apiDouble(),finished={...dto(),state:'finished' as const,revision:2,prompt_index:1,recap:{practiced_exercises:1,completed_attempts:1,focus:'Actual saved focus',next_practice:'Actual saved next step'}};const heartbeat=vi.spyOn(api,'heartbeat').mockResolvedValue(finished);const c=new VoiceSession(api,()=>{},d.deps);await c.start({scenario_id:'help-desk',goal:'Clarity',context:'',prompt_visible:true});await vi.advanceTimersByTimeAsync(2000);expect(c.view.session).toEqual(finished);expect(d.track.stop).toHaveBeenCalled();expect(d.audio.srcObject).toBeNull();expect(heartbeat).toHaveBeenCalledTimes(1);expect(vi.getTimerCount()).toBe(0);c.dispose(false);
});
it('refuses explicit reconnect after authoritative expiry without another SDP exchange',async()=>{
 const d=mediaDoubles(),api=apiDouble();const c=new VoiceSession(api,()=>{},d.deps);await c.start({scenario_id:'help-desk',goal:'Clarity',context:'',prompt_visible:false});vi.spyOn(api,'get').mockResolvedValue({...dto(),revision:2,expires_at:new Date(Date.now()-1).toISOString()});const command=vi.spyOn(api,'command');await c.action('reconnect');expect(command).not.toHaveBeenCalled();expect(api.connect).toHaveBeenCalledTimes(1);expect(d.track.stop).toHaveBeenCalled();expect(c.view.visible).toBe(false);c.dispose(false);
});
