import {afterEach,expect,it,vi} from 'vitest';
import {VoiceSession,VoiceTransport,assertAudioOnlySdp} from './voice-session';import {GuidedApi} from './guided-api';import {Api} from './api';
import {dto,mediaDoubles,deferred,audioSdp} from './guided-test-doubles';import type {GuidedSession} from './guided-types';
afterEach(()=>vi.useRealTimers());
// Test-only HTTP and peer doubles. No real account or provider requests.
function setup(){const d=mediaDoubles(),api=new GuidedApi(new Api(async()=>'test',vi.fn()));vi.spyOn(api,'create').mockResolvedValue(dto());vi.spyOn(api,'connect').mockResolvedValue({sdp:audioSdp,session:{...dto(),state:'coach_speaking',revision:1}});return {d,api};}
it('ends immediately during a lost SDP exchange, aborts that request and never accepts its late authoritative response',async()=>{
 const {d,api}=setup();const exchange=deferred<{sdp:string;session:GuidedSession}>();const connect=vi.spyOn(api,'connect').mockReturnValue(exchange.promise);const ended={...dto(),state:'finished' as const,revision:3};const command=vi.spyOn(api,'command').mockResolvedValue(ended);const c=new VoiceSession(api,()=>{},d.deps);const starting=c.start({scenario_id:'help-desk',goal:'Clarity',context:'',prompt_visible:true});await vi.waitFor(()=>expect(connect).toHaveBeenCalled());
 const finishing=c.action('finish');expect(d.track.stop).toHaveBeenCalled();await vi.waitFor(()=>expect(command).toHaveBeenCalledWith(expect.anything(),'finish',undefined,expect.any(AbortSignal)));await finishing;expect(c.view.session).toEqual(ended);expect(connect.mock.calls[0][2]?.aborted).toBe(true);exchange.resolve({sdp:audioSdp,session:{...dto(),state:'listening',revision:4}});await starting;expect(c.view.session).toEqual(ended);c.dispose(false);
});
it('resumes a paused authoritative session with a fresh microphone and new audio-only peer',async()=>{
 const {d,api}=setup();const paused={...dto(),state:'paused' as const,revision:2};vi.spyOn(api,'get').mockResolvedValue(paused);vi.spyOn(api,'command').mockImplementation(async(s,action)=>({...s,state:action==='pause'?'paused':'connecting',revision:s.revision+1}));const c=new VoiceSession(api,()=>{},d.deps);await c.start({scenario_id:'help-desk',goal:'Clarity',context:'',prompt_visible:false});await c.action('pause');vi.spyOn(api,'connect').mockResolvedValue({sdp:audioSdp,session:{...dto(),state:'coach_speaking',revision:4,prompt_visible:false}});await c.action('resume');expect(d.deps.getUserMedia).toHaveBeenCalledTimes(2);expect(api.connect).toHaveBeenCalledTimes(2);expect(d.audio.play).toHaveBeenCalledTimes(2);expect(c.view.transport).toBe('connected');expect(c.view.visible).toBe(false);c.dispose(false);
});
it('maintains the heartbeat lease while paused without reacquiring microphone or peer resources',async()=>{
 vi.useFakeTimers();const {d,api}=setup();const paused={...dto(),state:'paused' as const,revision:2};vi.spyOn(api,'command').mockResolvedValue(paused);vi.spyOn(api,'get').mockResolvedValue(paused);const heartbeat=vi.spyOn(api,'heartbeat').mockResolvedValue(paused);const c=new VoiceSession(api,()=>{},d.deps);await c.start({scenario_id:'help-desk',goal:'Clarity',context:'',prompt_visible:true});await c.action('pause');await vi.advanceTimersByTimeAsync(6000);expect(heartbeat).toHaveBeenCalledTimes(3);expect(d.deps.getUserMedia).toHaveBeenCalledTimes(1);expect(d.peer.addTrack).toHaveBeenCalledTimes(1);expect(d.track.enabled).toBe(false);c.dispose(false);expect(vi.getTimerCount()).toBe(0);
});
it('holds outbound audio muted across an in-flight poll until the mute command is confirmed',async()=>{
 vi.useFakeTimers();const {d,api}=setup();vi.spyOn(api,'connect').mockResolvedValue({sdp:audioSdp,session:{...dto(),state:'listening',revision:1}});const poll=deferred<GuidedSession>(),muted=deferred<GuidedSession>();vi.spyOn(api,'heartbeat').mockReturnValue(poll.promise);vi.spyOn(api,'command').mockReturnValue(muted.promise);const c=new VoiceSession(api,()=>{},d.deps);await c.start({scenario_id:'help-desk',goal:'Clarity',context:'',prompt_visible:true});await vi.advanceTimersByTimeAsync(2000);const muting=c.action('mute');expect(d.track.enabled).toBe(false);poll.resolve({...dto(),state:'listening',revision:2});await vi.advanceTimersByTimeAsync(600);expect(d.track.enabled).toBe(false);muted.resolve({...dto(),state:'listening',muted:true,revision:3});await muting;expect(d.track.enabled).toBe(false);c.dispose(false);
});
it('allows explicit recovery after an unconfirmed finish while keeping the previous media disconnected',async()=>{
 const {d,api}=setup();const live={...dto(),state:'listening' as const,revision:2};vi.spyOn(api,'get').mockResolvedValue(live);const command=vi.spyOn(api,'command').mockRejectedValueOnce(new Error('Network failure')).mockResolvedValue({...live,state:'reconnecting',revision:3});const c=new VoiceSession(api,()=>{},d.deps);await c.start({scenario_id:'help-desk',goal:'Clarity',context:'',prompt_visible:true});await c.action('finish');expect(d.track.stop).toHaveBeenCalled();expect(c.view.transport).toBe('disconnected');vi.spyOn(api,'connect').mockResolvedValue({sdp:audioSdp,session:{...live,state:'coach_speaking',revision:4}});await c.action('reconnect');expect(command).toHaveBeenCalledTimes(2);expect(c.view.transport).toBe('connected');c.dispose(false);
});
