import {act,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {expect,it,vi} from 'vitest';
import {GuidedSessionView,GuidedSnapshot,GuidedHistory} from './GuidedSessionView';
import {GuidedApi} from './guided-api';import {Api} from './api';
import {dto,mediaDoubles,audioSdp,deferred} from './guided-test-doubles';
import type {GuidedViewState} from './voice-session';
import type {GuidedSession} from './guided-types';
const rich=():GuidedSession=>{const s=dto();return {...s,state:'listening',revision:2,status_message:'PRIVATE TARGET status',goal:'PRIVATE TARGET goal',turns:[{id:'turn-a',prompt_id:'prompt-a',provider_item_id:'item-a',attempt:1,transcript:'PRIVATE TARGET transcript',prompt_visible:true,created_at:s.created_at,feedback:{prompt_id:'prompt-a',strength:'PRIVATE TARGET strength',priority_correction:'PRIVATE TARGET correction',corrected_example:'PRIVATE TARGET example',decision:'retry',evidence_basis:'transcript',evidence_quote:'PRIVATE TARGET quote',spoken_feedback:'PRIVATE TARGET spoken'}}],recap:{practiced_exercises:1,completed_attempts:1,focus:'PRIVATE TARGET focus',next_practice:'PRIVATE TARGET next'}};};
it('removes hidden target and reconstructive content from every DOM/accessibility surface rather than hiding with CSS',()=>{
 const view:GuidedViewState={session:rich(),visible:false,busy:false,error:'',audioBlocked:false,transport:'connected',remaining:42};const rendered=render(<GuidedSnapshot view={view} onAction={()=>{}} onVisibility={()=>{}} onRecover={()=>{}}/>);
 expect(rendered.container.innerHTML).not.toContain('PRIVATE TARGET');expect(screen.getByText('Prompt hidden. Listen to the coach.')).toBeInTheDocument();expect(screen.getByText('Correction available')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Show Prompt'})).toHaveAttribute('aria-pressed','false');expect(screen.getByText(/42 seconds/)).toBeInTheDocument();
 rendered.rerender(<GuidedSnapshot view={{...view,visible:true}} onAction={()=>{}} onVisibility={()=>{}} onRecover={()=>{}}/>);expect(screen.getByText('PRIVATE TARGET')).toBeInTheDocument();expect(screen.getByText('PRIVATE TARGET correction')).toBeInTheDocument();
});
it('never requests microphone permission on mount, unavailable configuration, or an unverified account',()=>{
 const d=mediaDoubles(),api=new GuidedApi(new Api(async()=>null,vi.fn()));const setup={scenario_id:'help-desk',goal:'Clarity',context:'',prompt_visible:true};const view=render(<GuidedSessionView api={api} setup={setup} available={false} verified={true} dependencies={d.deps}/>);expect(screen.getByText(/Guided Voice is unavailable/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Start guided session'})).toBeDisabled();view.rerender(<GuidedSessionView api={api} setup={setup} available verified={false} dependencies={d.deps}/>);expect(screen.getByRole('button',{name:'Start guided session'})).toBeDisabled();expect(d.deps.getUserMedia).not.toHaveBeenCalled();
});
it('keeps the same visibility control focused while a pending hide command safely suppresses feedback',async()=>{
 const d=mediaDoubles(),api=new GuidedApi(new Api(async()=>'test',vi.fn()));vi.spyOn(api,'create').mockResolvedValue(dto());vi.spyOn(api,'connect').mockResolvedValue({sdp:audioSdp,session:rich()});const pending=deferred<GuidedSession>();vi.spyOn(api,'command').mockReturnValue(pending.promise);
 const view=render(<GuidedSessionView api={api} setup={{scenario_id:'help-desk',goal:'Clarity',context:'',prompt_visible:true}} available verified dependencies={d.deps}/>);fireEvent.click(screen.getByRole('button',{name:'Start guided session'}));await screen.findByText('PRIVATE TARGET');const toggle=screen.getByRole('button',{name:'Hide Prompt'});toggle.focus();fireEvent.click(toggle);expect(document.activeElement).toBe(toggle);expect(view.container.innerHTML).not.toContain('PRIVATE TARGET');await act(async()=>{pending.resolve({...rich(),prompt_visible:false,revision:3});await pending.promise;});expect(d.peer.close).not.toHaveBeenCalled();view.unmount();
});
it('keeps active hidden prompts out of history and reads finished sessions back before verifying deletion',async()=>{
 const api=new GuidedApi(new Api(async()=>'test',vi.fn()));const ended={...rich(),id:'ended',state:'finished' as const};const list=vi.spyOn(api,'list').mockResolvedValue([rich(),ended]);const get=vi.spyOn(api,'get').mockResolvedValue(ended);const remove=vi.spyOn(api,'delete').mockResolvedValue(undefined);vi.spyOn(window,'confirm').mockReturnValue(true);
 const view=render(<GuidedHistory api={api} verified ownerKey="a"/>);await screen.findByRole('button',{name:'Review guided session'});expect(view.container.innerHTML).not.toContain('PRIVATE TARGET');fireEvent.click(screen.getByRole('button',{name:'Review guided session'}));await screen.findByText('PRIVATE TARGET');expect(get).toHaveBeenCalledWith('ended',expect.any(AbortSignal));list.mockResolvedValue([rich()]);fireEvent.click(screen.getByRole('button',{name:'Delete guided session ended'}));await waitFor(()=>expect(remove).toHaveBeenCalledWith('ended',expect.any(AbortSignal)));await waitFor(()=>expect(screen.queryByText('PRIVATE TARGET')).not.toBeInTheDocument());expect(list).toHaveBeenCalledTimes(2);
});
it('can cancel a pending microphone gesture and releases a late stream without creating a session',async()=>{
 const d=mediaDoubles(),permission=deferred<MediaStream>();d.deps.getUserMedia.mockReturnValue(permission.promise);const api=new GuidedApi(new Api(async()=>'test',vi.fn()));const create=vi.spyOn(api,'create');render(<GuidedSessionView api={api} setup={{scenario_id:'help-desk',goal:'Clarity',context:'',prompt_visible:true}} available verified dependencies={d.deps}/>);fireEvent.click(screen.getByRole('button',{name:'Start guided session'}));fireEvent.click(screen.getByRole('button',{name:'Cancel guided connection'}));await act(async()=>{permission.resolve(d.stream);await permission.promise;});expect(d.track.stop).toHaveBeenCalled();expect(create).not.toHaveBeenCalled();expect(screen.getByRole('button',{name:'Start guided session'})).toBeEnabled();
});
it('explains microphone permission failure without creating a persisted session or exposing provider details',async()=>{
 const d=mediaDoubles();d.deps.getUserMedia.mockRejectedValue(new Error('private device path'));const api=new GuidedApi(new Api(async()=>'test',vi.fn()));const create=vi.spyOn(api,'create');render(<GuidedSessionView api={api} setup={{scenario_id:'help-desk',goal:'Clarity',context:'',prompt_visible:true}} available verified dependencies={d.deps}/>);fireEvent.click(screen.getByRole('button',{name:'Start guided session'}));expect(await screen.findByRole('alert')).toHaveTextContent('Microphone permission');expect(screen.queryByText(/private device path/)).not.toBeInTheDocument();expect(create).not.toHaveBeenCalled();
});
it('never restores previous-owner guided history after a late list response',async()=>{
 const api=new GuidedApi(new Api(async()=>'test',vi.fn()));const old=deferred<GuidedSession[]>();vi.spyOn(api,'list').mockReturnValueOnce(old.promise).mockResolvedValue([]);const view=render(<GuidedHistory api={api} verified ownerKey="a"/>);view.rerender(<GuidedHistory api={api} verified ownerKey="b"/>);await act(async()=>{old.resolve([{...rich(),state:'finished'}]);await old.promise;});expect(screen.queryByRole('button',{name:'Review guided session'})).not.toBeInTheDocument();expect(view.container.innerHTML).not.toContain('PRIVATE TARGET');
});
it('suppresses target-derived recap, transcript, evidence, examples and feedback even after hidden completion',()=>{
 const view:GuidedViewState={session:{...rich(),state:'finished',prompt_index:1},visible:false,busy:false,error:'',audioBlocked:false,transport:'idle',remaining:0};const rendered=render(<GuidedSnapshot view={view} onAction={()=>{}} onVisibility={()=>{}} onRecover={()=>{}}/>);expect(rendered.container.innerHTML).not.toContain('PRIVATE TARGET');expect(screen.getByText(/1 exercises practiced/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'I’m done'})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Show Prompt'})).toBeEnabled();
});
it('does not retain prompts, transcript or feedback in any browser persistent storage during guided controls',async()=>{
 const storage=vi.spyOn(Storage.prototype,'setItem'),d=mediaDoubles(),api=new GuidedApi(new Api(async()=>'test',vi.fn()));vi.spyOn(api,'create').mockResolvedValue(dto());vi.spyOn(api,'connect').mockResolvedValue({sdp:audioSdp,session:rich()});vi.spyOn(api,'command').mockResolvedValue({...rich(),prompt_visible:false,revision:3});const view=render(<GuidedSessionView api={api} setup={{scenario_id:'help-desk',goal:'Clarity',context:'',prompt_visible:true}} available verified dependencies={d.deps}/>);fireEvent.click(screen.getByRole('button',{name:'Start guided session'}));await screen.findByText('PRIVATE TARGET');fireEvent.click(screen.getByRole('button',{name:'Hide Prompt'}));await waitFor(()=>expect(api.command).toHaveBeenCalled());expect(storage).not.toHaveBeenCalled();view.unmount();storage.mockRestore();
});
