export function validateRecording(blob:Blob,seconds:number,maxBytes=12582912){if(seconds<30||seconds>180)throw new Error('Record between 30 and 180 seconds.');if(!blob.size)throw new Error('Your recording is empty. Please check your microphone.');if(blob.size>maxBytes)throw new Error('Recording is too large. Please make a shorter recording.');}
export class RecordingController{
 private stream?:MediaStream;private recorder?:MediaRecorder;private timer?:ReturnType<typeof setTimeout>;private chunks:Blob[]=[];private started=0;private cancelled=false;
 constructor(private deps={getUserMedia:(c:MediaStreamConstraints)=>navigator.mediaDevices.getUserMedia(c),Recorder:globalThis.MediaRecorder}){}
 async start(onFinish:(blob:Blob,seconds:number)=>void){this.cancelled=false;if(!this.deps.Recorder)throw new Error('Recording is not supported in this browser. Use a current desktop Chrome, Firefox, or Safari.');this.stream=await this.deps.getUserMedia({audio:true});if(this.cancelled){this.release();return;}try{const type=['audio/webm;codecs=opus','audio/webm','audio/mp4','audio/ogg;codecs=opus'].find(t=>this.deps.Recorder.isTypeSupported(t));if(!type)throw new Error('No supported audio recording format is available.');this.chunks=[];this.recorder=new this.deps.Recorder(this.stream,{mimeType:type});this.recorder.ondataavailable=e=>{if(e.data.size)this.chunks.push(e.data)};this.recorder.onstop=()=>{const seconds=Math.min(180,(performance.now()-this.started)/1000);this.release();if(!this.cancelled)onFinish(new Blob(this.chunks,{type}),seconds);this.chunks=[];};this.started=performance.now();this.recorder.start(1000);this.timer=setTimeout(()=>this.stop(),180000);}catch(e){this.release();throw e;}}
 stop(){if(this.recorder?.state==='recording')this.recorder.stop();clearTimeout(this.timer);}
 cancel(){this.cancelled=true;this.stop();this.release();this.chunks=[];}
 private release(){clearTimeout(this.timer);this.stream?.getTracks().forEach(track=>track.stop());this.stream=undefined;}
}
