import {isGuidedEnded,type GuidedSession,type GuidedSetup,type GuidedAction} from './guided-types';
import {GuidedApi} from './guided-api';
export type VoiceDependencies={getUserMedia:(c:MediaStreamConstraints)=>Promise<MediaStream>;createPeer:()=>RTCPeerConnection;createAudio:()=>HTMLAudioElement;tailMs?:number;timeoutMs?:number};
const defaults:VoiceDependencies={getUserMedia:c=>navigator.mediaDevices.getUserMedia(c),createPeer:()=>new RTCPeerConnection(),createAudio:()=>new Audio(),tailMs:500,timeoutMs:12000};
class VoiceError extends Error{}
export function assertAudioOnlySdp(sdp:string){const media=sdp.split(/\r?\n/).filter(l=>l.startsWith('m='));if(!sdp.startsWith('v=0')||sdp.length>200000||media.length!==1||!/^m=audio (?!0(?:\s|$))\d+\s/.test(media[0])||/sctp|m=application|m=video/i.test(sdp))throw new VoiceError('Audio-only voice connection required.');}
export class VoiceTransport{
 private stream?:MediaStream;private remote?:MediaStream;private peer?:RTCPeerConnection;private audio?:HTMLAudioElement;private epoch=0;private abort=new AbortController();private tail?:ReturnType<typeof setTimeout>;private playback=false;private playbackVersion=0;private holding=false;private microphoneHold=false;private snapshot?:GuidedSession;
 constructor(private events:{onIssue?:(m:string)=>void;onAudioBlocked?:(blocked:boolean)=>void}={},private deps:VoiceDependencies=defaults){}
 // Called directly in a user gesture, before any slow API request.
 async acquire(){this.close();const epoch=this.epoch;let stream:MediaStream;try{stream=await this.deps.getUserMedia({audio:true});}catch{throw new VoiceError('Microphone permission or device access failed. Allow microphone access and start again.');}stream.getTracks().forEach(t=>{t.enabled=false;});if(epoch!==this.epoch){stream.getTracks().forEach(t=>t.stop());throw new Error('Voice connection cancelled.');}this.stream=stream;}
 private check(epoch:number){if(epoch!==this.epoch||this.abort.signal.aborted)throw new Error('Voice connection cancelled.');}
 private wait(peer:RTCPeerConnection,event:string,ready:()=>boolean){const signal=this.abort.signal;return new Promise<void>((resolve,reject)=>{let timer:ReturnType<typeof setTimeout>;const cleanup=()=>{clearTimeout(timer);peer.removeEventListener(event,changed);signal.removeEventListener('abort',cancelled);};const changed=()=>{if(ready()){cleanup();resolve();}else if(peer.connectionState==='failed'||peer.connectionState==='closed'){cleanup();reject(new VoiceError('Voice peer connection failed.'));}};const cancelled=()=>{cleanup();reject(new Error('Voice connection cancelled.'));};peer.addEventListener(event,changed);signal.addEventListener('abort',cancelled,{once:true});timer=setTimeout(()=>{cleanup();reject(new VoiceError('Voice connection timed out. Reconnect explicitly to try again.'));},this.deps.timeoutMs??12000);if(signal.aborted)cancelled();else changed();});}
 async connect(exchange:(sdp:string)=>Promise<string>){const epoch=this.epoch;this.check(epoch);if(!this.stream)throw new Error('Microphone access is required.');try{const peer=this.deps.createPeer();this.peer=peer;const audio=this.deps.createAudio();this.audio=audio;audio.autoplay=false;
 // No provider data channel: audio-only SDP prevents client-side response/session control.
 peer.ontrack=event=>{if(epoch!==this.epoch)return;this.remote=event.streams[0]??new MediaStream([event.track]);if(!this.holding){audio.srcObject=this.remote;void this.play();}};
 peer.onconnectionstatechange=()=>{if(epoch!==this.epoch)return;if(peer.connectionState==='disconnected'||peer.connectionState==='failed'){this.close();this.events.onIssue?.('Voice connection interrupted. Reconnect to restore the saved session.');}};
 this.stream.getAudioTracks().forEach(track=>peer.addTrack(track,this.stream!));
 const offer=await peer.createOffer();this.check(epoch);assertAudioOnlySdp(offer.sdp??'');await peer.setLocalDescription(offer);this.check(epoch);await this.wait(peer,'icegatheringstatechange',()=>peer.iceGatheringState==='complete');this.check(epoch);
 const sdp=peer.localDescription?.sdp??'';assertAudioOnlySdp(sdp);const answer=await exchange(sdp);this.check(epoch);assertAudioOnlySdp(answer);
 // Listener registered before applying answer (which can complete immediately).
 const connected=this.wait(peer,'connectionstatechange',()=>peer.connectionState==='connected');connected.catch(()=>{});await peer.setRemoteDescription({type:'answer',sdp:answer});await connected;this.check(epoch);this.gate();
 }catch(e){if(epoch===this.epoch)this.close();throw e;}}
 private async play(){const epoch=this.epoch;const version=++this.playbackVersion;const audio=this.audio;if(!audio||!this.remote||this.holding)return;try{await audio.play();this.check(epoch);if(version!==this.playbackVersion)return;this.playback=true;this.events.onAudioBlocked?.(false);this.gate();}catch{if(epoch===this.epoch&&version===this.playbackVersion){this.playback=false;this.disable();this.events.onAudioBlocked?.(true);}}}
 recoverAudio(){return this.play();}
 private disable(){clearTimeout(this.tail);this.tail=undefined;this.stream?.getTracks().forEach(t=>{t.enabled=false;});}
 private gate(){this.disable();const s=this.snapshot;if(!s||s.state!=='listening'||s.muted||!this.playback||this.holding||this.microphoneHold||this.peer?.connectionState!=='connected')return;const epoch=this.epoch;const revision=s.revision;this.tail=setTimeout(()=>{this.tail=undefined;if(epoch===this.epoch&&this.snapshot?.revision===revision&&this.snapshot.state==='listening'&&!this.snapshot.muted&&this.playback&&!this.holding&&!this.microphoneHold)this.stream?.getAudioTracks().forEach(t=>{t.enabled=true;});},this.deps.tailMs??500);}
 apply(s:GuidedSession){const prev=this.snapshot;this.snapshot=s;if(isGuidedEnded(s)||s.state==='paused'){this.close();return;}if(prev?.state!==s.state||prev?.muted!==s.muted||prev?.revision!==s.revision)this.gate();}
 muteImmediately(){this.microphoneHold=true;this.disable();}
 releaseMicrophoneHold(){this.microphoneHold=false;this.gate();}
 dropPlayback(){this.playbackVersion++;this.holding=true;this.playback=false;this.disable();this.audio?.pause();if(this.audio)this.audio.srcObject=null;}
 restorePlayback(){this.holding=false;if(this.audio&&this.remote){this.audio.srcObject=this.remote;return this.play();}return Promise.resolve();}
 close(){this.epoch++;this.abort.abort();this.abort=new AbortController();this.disable();this.stream?.getTracks().forEach(t=>t.stop());this.stream=undefined;if(this.peer){this.peer.ontrack=null;this.peer.onconnectionstatechange=null;this.peer.close();}this.peer=undefined;this.audio?.pause();if(this.audio){this.audio.srcObject=null;this.audio.remove();}this.audio=undefined;this.remote=undefined;this.playback=false;this.holding=false;this.microphoneHold=false;this.snapshot=undefined;}
}

export type GuidedViewState={session:GuidedSession|null;visible:boolean;busy:boolean;error:string;audioBlocked:boolean;transport:'idle'|'connecting'|'connected'|'disconnected';remaining:number};
export class VoiceSession{
 view:GuidedViewState={session:null,visible:true,busy:false,error:'',audioBlocked:false,transport:'idle',remaining:0};
 private transport:VoiceTransport;private lane:Promise<void>=Promise.resolve();private pending=0;private disposed=false;private operation=0;private finishing=false;private abort=new AbortController();private poll?:ReturnType<typeof setInterval>;private timers=new Set<ReturnType<typeof setTimeout>>();private owner:unknown;
 constructor(private api:GuidedApi,private update:(state:GuidedViewState)=>void,dependencies?:VoiceDependencies,private ownerScope:()=>unknown=()=>null){this.owner=ownerScope();this.transport=new VoiceTransport({onIssue:m=>{this.stopPoll();this.view={...this.view,transport:'disconnected',error:m};this.emit();},onAudioBlocked:blocked=>{this.view={...this.view,audioBlocked:blocked};this.emit();}},dependencies);}
 private valid(){if(this.disposed)return false;if(this.owner!==this.ownerScope()){this.dispose(false);return false;}return true;}
 private check(){if(!this.valid())throw new Error('Voice operation cancelled.');}
 private emit(){if(this.valid())this.update({...this.view});}
 private async request<T>(work:(signal:AbortSignal)=>Promise<T>):Promise<T>{this.check();const parent=this.abort.signal;const child=new AbortController();const cancel=()=>child.abort();let rejectAbort:()=>void=()=>{};const cancelled=new Promise<never>((_,reject)=>{rejectAbort=()=>reject(new VoiceError('Voice operation cancelled or timed out.'));});child.signal.addEventListener('abort',rejectAbort,{once:true});parent.addEventListener('abort',cancel,{once:true});const timer=setTimeout(cancel,12000);this.timers.add(timer);try{if(parent.aborted)cancel();const result=await Promise.race([work(child.signal),cancelled]);this.check();if(child.signal.aborted)throw new Error('Voice operation cancelled or timed out.');return result;}finally{clearTimeout(timer);this.timers.delete(timer);parent.removeEventListener('abort',cancel);child.signal.removeEventListener('abort',rejectAbort);}}
 private accept(s:GuidedSession,syncMedia=true){this.check();if(this.view.session&&s.revision<this.view.session.revision)return;this.view={...this.view,session:s,remaining:Math.max(0,Math.ceil((Date.parse(s.expires_at)-Date.now())/1000))};if(syncMedia||isGuidedEnded(s))this.transport.apply(s);if(isGuidedEnded(s)){this.stopPoll();this.view={...this.view,transport:'idle'};}this.emit();}
 private enqueue(work:()=>Promise<void>,reconcile=true,stopOnError=false){if(!this.valid())return Promise.resolve();this.pending++;this.view={...this.view,busy:true,error:''};this.emit();const operation=this.operation;const task=this.lane.then(async()=>{this.check();if(operation!==this.operation)return;await work();}).catch(async(e:unknown)=>{if(!this.valid()||operation!==this.operation)return;if(stopOnError){this.transport.close();this.stopPoll();this.view={...this.view,transport:'disconnected'};}if(reconcile&&this.view.session){try{this.accept(await this.request(signal=>this.api.get(this.view.session!.id,signal)));}catch{/* Keep the last validated snapshot, not an invented state. */}}this.view={...this.view,error:e instanceof VoiceError?e.message:'Action was not confirmed. The saved session was reloaded when possible. No turn was automatically replayed; review the current state before trying another action.'};this.emit();}).finally(()=>{this.pending--;if(operation===this.operation&&this.view.session&&!isGuidedEnded(this.view.session))this.finishing=false;if(this.valid()){this.view={...this.view,busy:this.pending>0};this.emit();}});this.lane=task.catch(()=>{});return task;}
 private async connect(){this.check();const s=this.view.session;if(!s||isGuidedEnded(s)||Date.parse(s.expires_at)<=Date.now())throw new Error('Saved session has ended or expired.');this.view={...this.view,transport:'connecting'};this.emit();await this.transport.connect(async sdp=>{const result=await this.request(signal=>this.api.connect(this.view.session!,sdp,signal));this.accept(result.session);return result.sdp;});this.check();this.view={...this.view,transport:'connected'};if(this.view.session)this.transport.apply(this.view.session);this.emit();this.startPoll();}
 start(input:GuidedSetup){if(this.pending||this.view.session||!this.valid())return Promise.resolve();this.view={...this.view,visible:input.prompt_visible,transport:'connecting'};const permission=this.transport.acquire();permission.catch(()=>{});return this.enqueue(async()=>{try{await permission;this.check();this.accept(await this.request(signal=>this.api.create(input,signal)));await this.connect();}catch(e){this.transport.close();throw e;}},true,true);}
 toggle(visible:boolean){this.view={...this.view,visible};this.emit();if(!this.view.session||isGuidedEnded(this.view.session))return Promise.resolve();return this.enqueue(async()=>{this.accept(await this.request(signal=>this.api.command(this.view.session!,'visibility',visible,signal)));},true);}
 action(action:GuidedAction){if(!this.valid()||this.finishing||!this.view.session||isGuidedEnded(this.view.session))return Promise.resolve();if(action==='pause'||action==='finish'){if(action==='finish')this.finishing=true;this.operation++;this.abort.abort();this.abort=new AbortController();this.transport.close();this.stopPoll();this.view={...this.view,transport:'idle',audioBlocked:false};this.emit();}else if(action==='mute'||action==='done')this.transport.muteImmediately();else if(action==='replay'||action==='retry')this.transport.dropPlayback();
 // Resume/reconnect are explicit gestures. Permission starts now, not after GET/commands.
 const permission=action==='resume'||action==='reconnect'?this.transport.acquire():null;permission?.catch(()=>{});
 return this.enqueue(async()=>{if(permission){await permission;this.check();this.accept(await this.request(signal=>this.api.get(this.view.session!.id,signal)),false);if(isGuidedEnded(this.view.session!)||Date.parse(this.view.session!.expires_at)<=Date.now()){this.transport.close();throw new Error('Saved session has ended or expired.');}}
 this.accept(await this.request(signal=>this.api.command(this.view.session!,action,undefined,signal)));if(action==='mute'||action==='unmute'||action==='done')this.transport.releaseMicrophoneHold();
 if(permission)await this.connect();else if(action==='replay'||action==='retry')await this.transport.restorePlayback();else if(action==='pause'&&this.view.session&&!isGuidedEnded(this.view.session))this.startPoll();
 },true,action!=='visibility'&&action!=='mute'&&action!=='unmute');}
 recoverAudio(){return this.transport.recoverAudio();}
 private startPoll(){this.stopPoll();this.poll=setInterval(()=>{if(!this.valid()||!this.view.session||isGuidedEnded(this.view.session)){this.stopPoll();return;}this.view={...this.view,remaining:Math.max(0,Math.ceil((Date.parse(this.view.session.expires_at)-Date.now())/1000))};this.emit();if(this.pending)return;void this.enqueue(async()=>{this.accept(await this.request(signal=>this.api.heartbeat(this.view.session!.id,signal)));},false,true);},2000);}
 private stopPoll(){clearInterval(this.poll);this.poll=undefined;}
 dispose(finish=true){if(this.disposed)return;const s=this.view.session;const sameOwner=this.owner===this.ownerScope();this.disposed=true;this.transport.close();this.stopPoll();this.abort.abort();this.timers.forEach(clearTimeout);this.timers.clear();if(finish&&sameOwner&&s&&!isGuidedEnded(s)){const abort=new AbortController();const timeout=setTimeout(()=>abort.abort(),3000);void this.api.command(s,'finish',undefined,abort.signal).catch(()=>{}).finally(()=>clearTimeout(timeout));}}
}
